services:
  vacation-calculator:
    build: .
    container_name: vacation-calculator
    ports:
      - 8080:8081
    environment:
      SERVER_PORT: 8081
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10